// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtUL0NuVFS02XxbMUHME50c54ikqbNDBg',
    appId: '1:107878050458:web:53ec6c060ff0e589690d23',
    messagingSenderId: '107878050458',
    projectId: 'warmindotugas',
    authDomain: 'warmindotugas.firebaseapp.com',
    storageBucket: 'warmindotugas.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBNXwhSsuw4gfJdVBhq6ky6J8-Ik8g1dY',
    appId: '1:107878050458:android:59bfa03199bcdcf7690d23',
    messagingSenderId: '107878050458',
    projectId: 'warmindotugas',
    storageBucket: 'warmindotugas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3O8WG3AsMymjbNEy5ilrkcL0jwWNzw-8',
    appId: '1:107878050458:ios:bfd9dba22517cb9e690d23',
    messagingSenderId: '107878050458',
    projectId: 'warmindotugas',
    storageBucket: 'warmindotugas.appspot.com',
    iosBundleId: 'com.example.warmindoTugas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3O8WG3AsMymjbNEy5ilrkcL0jwWNzw-8',
    appId: '1:107878050458:ios:78bf32bbc1b5a364690d23',
    messagingSenderId: '107878050458',
    projectId: 'warmindotugas',
    storageBucket: 'warmindotugas.appspot.com',
    iosBundleId: 'com.example.warmindoTugas.RunnerTests',
  );
}
